Replace the two first implicit_wait with WebDriverWait for billetweb
trouver-une-fresque/trouver-une-fresque pull request #10
Opened 2024-01-12 17:49 UTC by csauge

- It reduces the **processing time by 50%** (from 16min to 8min)
- The WebDriverWait robustness helps to **capture +20% results in json** (4300 lines to 5600 lines)
- Remove multi and filter tests because seems useless (You confirm Thomas ?)

2024-01-12 18:13 UTC, csauge commented
not sure about "The WebDriverWait robustness helps to capture +20% results in json (4300 lines to 5600 lines)".
It seems that the results are not deterministics.
But this is at least as good :)

2024-01-13 12:30 UTC, csauge commented
I think you can try to deliver this (after your test of course), because my next step would be to manage the calendar in billetweb (which seems not easy)

2024-01-20 11:00 UTC, thomas-bouvier requested changes
Merci pour ton travail @csauge. On gagne en performance et en exhaustivité, ce qui est génial. On peut discuter sous mes commentaires !

2024-01-20 15:39 UTC, csauge commented on scraper/billetweb.py
> -                        continue
OK

2024-01-20 15:39 UTC, csauge commented on scraper/billetweb.py
> +            event_id = re.search(r"/([^/]+?)&", link).group(1)
OK

2024-01-20 15:39 UTC, csauge commented on scraper/billetweb.py
> +            description = even_el.text
OK

2024-01-20 15:39 UTC, csauge commented on scraper/billetweb.py
> -
OK

2024-01-20 15:40 UTC, csauge commented on utils/readJson.py
> -    cod_dep = department_code(postcode)
Comme convenu on le garde dans le PR

2024-01-20 15:40 UTC, csauge commented on utils/readJson.py
> +        cod_dep = data["features"][0]["properties"]["context"].split(',')[0].strip()
Comme convenu on le garde dans le PR

2024-01-20 15:42 UTC, csauge commented on utils/readJson.py
> +    params = {"q": text_address, "limit": 1}
Permet de garder seulement le premier résultat (suffisant aujourd'hui)

2024-01-20 15:44 UTC, csauge commented on scraper/billetweb.py
> -                    sold_out = "complet" in title.lower()
en fait l'existance meme de div.block suffit à dire que c'est sold out (full or waiting list). seul un cas (géré) permet de dire que ce n'est pas sold out si l'evenement est à payer par un autre moyen (par exemple vers un autre site)

2024-01-20 15:44 UTC, csauge commented on data/codepostal_to_insee.json
Comme convenu on le garde dans le PR

2024-01-20 15:44 UTC, csauge commented on data/insee_to_codepostal_and_code_departement.json
Comme convenu on le garde dans le PR

2024-01-20 15:44 UTC, csauge commented on scraper/billetweb.py
> +                print(f"\n-> Processing {title}, {event_time}, {full_location}, {sold_out}, {ticket_link}, {uuid} ...")
OK

2024-01-20 15:45 UTC, csauge commented on scraper/billetweb.py
> +                    event_end_datetime = event_start_datetime + timedelta(hours=3)
Oui tous les cas sont bien gérés

2024-01-20 15:45 UTC, csauge commented on scraper/billetweb.py
> +            sessions_ele = driver.find_elements(By.CSS_SELECTOR, 'a.sesssion_href')
Bizarre mais oui :)

2024-01-20 15:56 UTC, csauge commented on scraper/billetweb.py
> +                    # FEATURES TO ADD: manage outside france, timezones, number of remainings, price
OK. I have created 2 PR for this comments to manage

2024-01-20 19:57 UTC, merged

2024-01-20 19:59 UTC, thomas-bouvier commented
Ferme #3. Merci beaucoup pour ton travail @csauge, nous passons de ~ateliers en présentiel recensés à presque 800.